name: Release Script

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update script version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          sed -i '' "s/^VERSION=\".*\"/VERSION=\"$TAG\"/" laravel-sync

      - name: Push the version hardcoded
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add laravel-sync
          git commit -m "chore: bump to version $TAG"
          git push origin HEAD:main

      - name: Crea release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Automatic release for ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
